### ISSUE TITLE
core 1: panicked at src/kernel/proc.rs:726:5

### ISSUE THREAD

**Issue by 707state** [o8vm/octox#24]
```text
bd: memory sz is 535633920 bytes; allocate an size array of length 26
bd: 12584176 meta bytes for managing 536870912 bytes of memory
bd: 1236992 bytes unavailable
hart 2 starting
hart 1 starting
hart 3 starting
usertrap(): unexcepted scause Exception(StorePageFault), pid=PId(0)
            sepc=5C4, stval=B040
core 1: panicked at src/kernel/proc.rs:726:5:
init exiting
```

Toolchain: Rust nightly
OS: Arch Linux

using cargo run --target riscv64gc-unknown-none-elf and it fails

**Comment by o8vm** [comment]
thanks for reporting! this is related to #23 .
