### ISSUE TITLE
build.rs with rustc 1.73.0-nightly panics

### ISSUE THREAD

**Issue by papparapa** [o8vm/octox#6]
## Description

`cargo build` using rustc 1.73.0-nightly (e4c144684 2023-08-04) panics.
I confirmed that adding the line `#![allow(internal_features)]` to src/user/lib.rs fixes this issue.
I can send a PR if you'd like though I read that you will not accept PRs.

## Log

```bash
$ RUST_BACKTRACE=full cargo build --target riscv64gc-unknown-none-elf -j 1
   Compiling octox v0.1.0 (/workspaces/Octox/octox)
error: failed to run custom build command for `octox v0.1.0 (/workspaces/Octox/octox)`

Caused by:
  process didn't exit successfully: `/workspaces/Octox/octox/target/debug/build/octox-a17854ef5802c003/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/workspaces/Octox/octox/src/user
  [uprogs 0.1.0] cargo:rustc-link-arg=-T/workspaces/Octox/octox/src/user/user.ld

  --- stderr
    Installing uprogs v0.1.0 (/workspaces/Octox/octox/src/user)
         Fresh libkernel v0.1.0 (/workspaces/Octox/octox/src/kernel)
         Dirty uprogs v0.1.0 (/workspaces/Octox/octox/src/user): the precalculated components changed
     Compiling uprogs v0.1.0 (/workspaces/Octox/octox/src/user)
       Running `/workspaces/Octox/octox/target/release/build/uprogs-c64ed7c102522f3f/build-script-build`
       Running `CARGO=/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=ulib CARGO_MANIFEST_DIR=/workspaces/Octox/octox/src/user CARGO_PKG_AUTHORS='Hayato Ohhashi <o8@vmm.dev>' CARGO_PKG_DESCRIPTION='octox user programs' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT/Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=uprogs CARGO_PKG_README='' CARGO_PKG_REPOSITORY='https://github.com/o8vm/octox' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/workspaces/Octox/octox/target/release/deps:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/workspaces/Octox/octox/target/debug/deps:/workspaces/Octox/octox/target/debug:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' OUT_DIR=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/build/uprogs-51b3e4d03d117abe/out /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name ulib --edition=2021 src/user/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=720243d35b109560 -C extra-filename=-720243d35b109560 --out-dir /workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps --target riscv64gc-unknown-none-elf -L dependency=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps -L dependency=/workspaces/Octox/octox/target/release/deps --extern kernel=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps/libkernel-0da9291a4951620f.rmeta -C link-arg=-T/workspaces/Octox/octox/src/user/user.ld`
  error: the feature `lang_items` is internal to the compiler or standard library
   --> src/user/lib.rs:2:12
    |
  2 | #![feature(lang_items, never_type, allocator_api, alloc_error_handler)]
    |            ^^^^^^^^^^
    |
    = note: using it is strongly discouraged
    = note: `#[deny(internal_features)]` on by default

  error: could not compile `uprogs` (lib) due to previous error

  Caused by:
    process didn't exit successfully: `CARGO=/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=ulib CARGO_MANIFEST_DIR=/workspaces/Octox/octox/src/user CARGO_PKG_AUTHORS='Hayato Ohhashi <o8@vmm.dev>' CARGO_PKG_DESCRIPTION='octox user programs' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT/Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=uprogs CARGO_PKG_README='' CARGO_PKG_REPOSITORY='https://github.com/o8vm/octox' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/workspaces/Octox/octox/target/release/deps:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/workspaces/Octox/octox/target/debug/deps:/workspaces/Octox/octox/target/debug:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' OUT_DIR=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/build/uprogs-51b3e4d03d117abe/out /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name ulib --edition=2021 src/user/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=720243d35b109560 -C extra-filename=-720243d35b109560 --out-dir /workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps --target riscv64gc-unknown-none-elf -L dependency=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps -L dependency=/workspaces/Octox/octox/target/release/deps --extern kernel=/workspaces/Octox/octox/target/riscv64gc-unknown-none-elf/release/deps/libkernel-0da9291a4951620f.rmeta -C link-arg=-T/workspaces/Octox/octox/src/user/user.ld` (exit status: 1)
  error: failed to compile `uprogs v0.1.0 (/workspaces/Octox/octox/src/user)`, intermediate artifacts can be found at `/workspaces/Octox/octox/target`.
  To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
  thread 'main' panicked at build.rs:71:9:
  failed to build user programs
  stack backtrace:
     0:     0x559160c07ccc - std::backtrace_rs::backtrace::libunwind::trace::he9d937609af5d283
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x559160c07ccc - std::backtrace_rs::backtrace::trace_unsynchronized::h9ca362d48127aa92
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x559160c07ccc - std::sys_common::backtrace::_print_fmt::he23d143b75ee23c2
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x559160c07ccc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2f2eede315027e39
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x559160c2bbdc - core::fmt::rt::Argument::fmt::h21248720ebffe7a2
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/core/src/fmt/rt.rs:138:9
     5:     0x559160c2bbdc - core::fmt::write::he255685ca7dc01db
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/core/src/fmt/mod.rs:1094:21
     6:     0x559160c053ee - std::io::Write::write_fmt::ha99dd1a6b5dc52ae
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/io/mod.rs:1714:15
     7:     0x559160c07ab5 - std::sys_common::backtrace::_print::h7f9139a3f45d6f8a
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x559160c07ab5 - std::sys_common::backtrace::print::h9b2270edc0141050
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x559160c098fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::h00b903f9ad480571
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:278:22
    10:     0x559160c09593 - std::panicking::panic_hook_with_disk_dump::h7abb3987b9874aaf
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:312:9
    11:     0x559160c09efb - std::panicking::default_hook::h920334edda857232
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:239:5
    12:     0x559160c09efb - std::panicking::rust_panic_with_hook::ha23d309026dae624
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:729:13
    13:     0x559160c09db1 - std::panicking::begin_panic_handler::{{closure}}::h7049679727d47105
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:619:13
    14:     0x559160c08206 - std::sys_common::backtrace::__rust_end_short_backtrace::h2217e53ad692d21e
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:170:18
    15:     0x559160c09b42 - rust_begin_unwind
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:617:5
    16:     0x559160bd5203 - core::panicking::panic_fmt::hb08a65af7de89c1c
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/core/src/panicking.rs:67:14
    17:     0x559160bd6eca - build_script_build::build_uprogs::h916f312c82ca72e3
                                 at /workspaces/Octox/octox/build.rs:71:9
    18:     0x559160bd628d - build_script_build::main::h80eb70c564043429
                                 at /workspaces/Octox/octox/build.rs:11:37
    19:     0x559160be2f7b - core::ops::function::FnOnce::call_once::h9f791f2c3c5a6393
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/core/src/ops/function.rs:250:5
    20:     0x559160bd79ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h4613b34bfd546a90
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/sys_common/backtrace.rs:154:18
    21:     0x559160bdb690 - std::rt::lang_start::{{closure}}::hcd5fb19942131e1f
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/rt.rs:166:18
    22:     0x559160c01deb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hdae8d374eb3ce8a3
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/core/src/ops/function.rs:284:13
    23:     0x559160c01deb - std::panicking::try::do_call::h579d42ec952c0840
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:524:40
    24:     0x559160c01deb - std::panicking::try::h4c798312ac538a1d
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:488:19
    25:     0x559160c01deb - std::panic::catch_unwind::h814c8a9d8e0938e1
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panic.rs:142:14
    26:     0x559160c01deb - std::rt::lang_start_internal::{{closure}}::hcd3527f49f7be08e
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/rt.rs:148:48
    27:     0x559160c01deb - std::panicking::try::do_call::h483d2d0aa0ccff7a
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:524:40
    28:     0x559160c01deb - std::panicking::try::ha83241dbd898e258
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panicking.rs:488:19
    29:     0x559160c01deb - std::panic::catch_unwind::hea44395d27c59c4f
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/panic.rs:142:14
    30:     0x559160c01deb - std::rt::lang_start_internal::h3903e979c479546b
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/rt.rs:148:20
    31:     0x559160bdb66a - std::rt::lang_start::hbe288964f5a42f10
                                 at /rustc/e4c14468460b22ac7a289a422fb7fee606e12a0b/library/std/src/rt.rs:165:17
    32:     0x559160bd770e - main
    33:     0x7ff057051b4a - __libc_start_call_main
    34:     0x7ff057051c0b - __libc_start_main@@GLIBC_2.34
    35:     0x559160bd58a5 - _start
    36:                0x0 - <unknown>
```

## Version

```bash
$ cat /etc/fedora-release
Fedora release 38 (Thirty Eight)
$ rustc --version
rustc 1.73.0-nightly (e4c144684 2023-08-04)
```

**Comment by o8vm** [comment]
Thank you for confirming. I would be very happy if you could send us a pull request!
I intend to change the policy about PRs in the future.

**Comment by o8vm** [comment]
Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as MIT and Apache-2.0, without any additional terms or conditions.
